# Generated by Django 3.2.10 on 2021-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=10, verbose_name='id')),
                ('type_name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.AlterField(
            model_name='firms',
            name='firm_id',
            field=models.CharField(max_length=10, verbose_name='id'),
        ),
    ]
