# Generated by Django 3.2.10 on 2021-12-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20211212_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firms',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technic_id', models.CharField(max_length=10, verbose_name='id')),
                ('technic_name', models.CharField(max_length=50, verbose_name='name')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.firms')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.types')),
            ],
        ),
    ]
